SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO, (
    SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME, AI.DATETIME, AI.SEX_UPON_INTAKE
    FROM ANIMAL_INS AI
    WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%'
    ) AII
WHERE AO.ANIMAL_ID = AII.ANIMAL_ID AND (AO.SEX_UPON_OUTCOME LIKE 'Spayed%' or AO.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY AO.ANIMAL_ID;