-- 오라클에선 DATE 타입으로 유지하면서 출력 포맷을 유지할수 있는 방법이 없는듯 하다. ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD'; 은 권한이 없음
SELECT MEMBER_ID, MEMBER_NAME, GENDER,
TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH,'MM') = '03'
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;