SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM (  
        SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
        FROM USED_GOODS_BOARD
        WHERE STATUS = 'DONE'
        GROUP BY WRITER_ID
    ) UBU,
     USED_GOODS_USER UGU
WHERE UBU.WRITER_ID = UGU.USER_ID AND TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;

