SELECT UB.TITLE, UB.BOARD_ID, UR.REPLY_ID, UR.WRITER_ID, UR.CONTENTS,
TO_CHAR(UR.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD UB
INNER JOIN USED_GOODS_REPLY UR
ON UB.BOARD_ID = UR.BOARD_ID
-- WHERE TO_CHAR(UR.CREATED_DATE,'YYYY-MM-DD') LIKE '2022-10-%'
WHERE UB.CREATED_DATE 
BETWEEN TO_DATE('20221001','YYYY-MM-DD') AND TO_DATE('20221031','YYYY-MM-DD')
ORDER BY UR.CREATED_DATE ASC, UB.TITLE ASC;